openapi: 3.0.0
info:
  title: Social Media Dashboard API
  version: 1.0.0
  description: API documentation for the Social Media Dashboard project
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - username
        - password
        - firstName
      properties:
        username:
          type: string
          minLength: 4
          maxLength: 20
          pattern: "^[a-zA-Z0-9_]+$"
          description: "Username must be between 4-20 characters and only contain letters, numbers, or underscores."
        password:
          type: string
          minLength: 8
          maxLength: 64
          pattern: "^(?=.*?[0-9])(?=.*?[#?!@$%^&*-_]).{8,}$"
          description: "Password must be between 8-64 characters, include at least one number and one special character."
        firstName:
          type: string
          minLength: 1
          maxLength: 50
          description: "First name of the user."
        lastName:
          type: string
          maxLength: 50
          description: "Last name of the user."
        avatar:
          type: string
          format: url
          description: "URL for the user's avatar."
  responses:
    500UnexpectedError:
      description: "An unexpected error occurred"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "An unexpected error occurred."

security:
  - bearerAuth: [ ]
servers:
  - url: http://localhost:8080
paths:
  /auth/register:
    post:
      summary: "Register a new user"
      description: "Endpoint to create a new user account"
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: "User created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User created successfully."
        '400':
          description: "Validation failed"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Validation failed."
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                        example: "Field must not be empty."
        '500':
          $ref: "#/components/responses/500UnexpectedError"
  /auth/login:
    post:
      summary: "Login user"
      description: "Endpoint to authenticate user and generate tokens"
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  minLength: 4
                  maxLength: 20
                  pattern: "^[a-zA-Z0-9_]+$"
                  description: "The user's username."
                password:
                  type: string
                  minLength: 8
                  maxLength: 64
                  pattern: "^(?=.*?[0-9])(?=.*?[#?!@$%^&*-_]).{8,}$"
                  description: "The user's password."
      responses:
        '200':
          description: "Login successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: "Access token for authentication."
        '400':
          description: "Validation failed"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Validation failed."
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                        example: "Field must not be empty."
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid credentials."
        '500':
          $ref: "#/components/responses/500UnexpectedError"
  /auth/logout:
    post:
      summary: "Log out user"
      description: "Endpoint to log out a user and clear their refresh token cookie"
      tags:
        - Authentication
      responses:
        '204':
          description: "Logged out successfully."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logged out successfully."
        '400':
          description: "No refresh token in request."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "No refresh token present."
        '500':
          $ref: "#/components/responses/500UnexpectedError"
  /auth/refreshToken:
    post:
      summary: "Refresh access token"
      description: "Endpoint to refresh a user's expired access token using a valid refresh token"
      tags:
        - Authentication
      responses:
        '200':
          description: "Access token refreshed successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: "The new access token for authentication."
        '401':
          description: "No refresh token provided or invalid refresh token"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Refresh token is missing."
        '403':
          description: "Refresh token is invalid or user does not exist"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "nvalid refresh token or user not found."
        '500':
          $ref: "#/components/responses/500UnexpectedError"
